# Multiple notifications bug: https://github.com/argoproj-labs/argocd-notifications/issues/90
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    myUsername: "Michele Mastrogiovanni"
  service.webhook.webhook-site: |
    url: "https://discordapp.com/api/webhooks/961751985978232882/cyE_bmgBCr0IKargEcw6h1wP2Urbu4yyPUlJ9aqYWOa5Lp2SsPUt-3kDNlhzqpi_30lC"
    headers:
    - name: Content-Type
      value: application/json
  template.app-sync-succeeded: |
    webhook:
      webhook-site:
        method: POST
        body: |
          {
            "message": "Congrats {{.context.myUsername}}! You synced you application successfully!"
          }
